### ISSUE TITLE
Horizontal scrolling/swiping does not respect the Natural Scrolling option in the Mouse & Touchpad System Settings

### ISSUE THREAD

**Issue by ddnexus** [passingthru67/workspaces-to-dock#100]
###Linux Distribution version
Ubuntu-Gnome

###Gnome Shell version
3.24

###Extension version or branch
latest

###Description of the problem
Swiping/scrolling left and right (horizontal switching enabled) doesn't respect the natural scrolling option in Mouse & Touchpad System Settings. The scrolling should move the content, not the view. As the result you must remember that you have to scroll the opposite direction than in all the rest of the system. Very annoying. The problem extends to the regular system gesture that should switch next/previous workspace. By enabling the horizontal scrolling it gets inverted too. If you was swiping up to go to the next workspace, the same gesture will scroll to the previous one! Very confusing.

###Steps to reproduce the problem
Show the doc at the bottom, enable thumbnails, enable Horizontal Switching option. Enable Natural scrolling in Mouse & Touchpad System Settings. Swipe left and right.

###Workaround
Using Libinput Gestures, and inverting the direction of the swiping. However, the scrolling is still inverted.

**Comment by passingthru67** [comment]
Out of curiosity, does the vertical scrolling respect the touchpad settings?

**Comment by passingthru67** [comment]
Ok, I think I fixed it.

Download the fix-touchpad branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/fix-touchpad.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r) and test to make sure the issue is gone.

Let me know how it turns out.

**Comment by ddnexus** [comment]
That fixed it!
Thank you for your super fast reaction and fix!

**Comment by adityaU** [comment]
Not working in Gnome shell 3.32 ubuntu 19.04. can't find the fix-touchpad branch either.
