### ISSUE TITLE
Triggers Gnome Shell / Wayland crash on Gnome 3.26

### ISSUE THREAD

**Issue by sha-red** [passingthru67/workspaces-to-dock#131]
###Linux Distribution version
Arch

###Gnome Shell version
GNOME Shell 3.26.2

###Xorg or Wayland (or both)
Wayland

###Extension version or branch
Most recent from extensions.gnome.org

###Description of the problem
On current gnome-shell/wayland having workspaces-to-dock enabled randomly triggers a crash/deadlock of gnome-shell, which then triggers a crash of wayland. The GUI completely freezes, 
Before this happens, the whole GUI get's slower and slower so it seems there is a memory leak somewhere. It's possible the ssh into the machine and kill gnome-shell.

I had those problems starting in early october, it took a long while to narrow it down.

###Steps to reproduce the problem

**Comment by sha-red** [comment]
Issue is not solely related to workspaces-to-dock.

**Comment by javenschuetz** [comment]
Not sure if its related, but when using the +/- buttons in tweak tool to configure this it regularly freezes the gui for up to 20 seconds when changing icon sizes and the system seems to get a little laggy after it happens enough times. A memory leak sounds plausible.

Later, after rebooting, was unable to load gnome after login when using wayland: mouse won't move, black/gray screen, eventually boots me to login screen. Switching back to xorg let me log in but it was slow: could move mouse cursor, but same black/grey screen, not stuck there though. Able to access the desktop after. Disabling the extension fixed it. Its a lovely extension though.

PopOS 17.10, first with wayland, then with xorg, gnome 3.26

-a fan

**Comment by passingthru67** [comment]
Anybody still having slowdown and lockup issues? If so, I'm gonna need more information to do any type of troubleshooting. We can start with a dump of your current WtD configuration. Simply type the following in the command line and then copy/paste the output here.

dconf dump /org/gnome/shell/extensions/workspaces-to-dock/

Something else to try is resetting the WtD configuration and testing again (especially if you run a distro system upgrade rather than install from scratch). You can do it by typing the following on the command line ..

dconf reset -f /org/gnome/shell/extensions/workspaces-to-dock/
