### ISSUE TITLE
Issue while moving cursor to second monitor

### ISSUE THREAD

**Issue by gliwka** [passingthru67/workspaces-to-dock#23]
Hello,

while trying to move the cursor to the second monitor with autohide + pressure enabled it get's stuck because of the workspaces dock and the pressure detection. One is only able to proceed to the second screen after the dock is fully visible. 

I would suggest to resolve this issue by adding a mouse speed threshold to the pressure detection, so fast movements do not trigger the dock to open and thus enable easy interaction with the second screen.

Kind regards
Matt

**Comment by passingthru67** [comment]
I may have a solution to this problem. But, now that we have the ability of positioning the dock at different screen locations (left/top/right/bottom), is it even a big issue anymore? Anybody want to chime in?

**Comment by kubecz3k** [comment]
@passingthru67 For me it would be very nice enhancement if it's possible. I'm addicted from the dock on the right (muscle memory almost) and recently I got second screen also on the right..

**Comment by passingthru67** [comment]
Okay, let me start by explaining a few things. Currently, to move the mouse or drag windows to a second monitor beyond the dock's pressure barrier, there are two options.

1) Toggle Gnome Shell's overview mode and drag the window to the second monitor.
2) Toggle the dock using the keyboard shortcut keys (default is Super+w) until it is shown and then drag the window to the second monitor

Note that in each of the above cases the dock is shown and thus the pressure barrier is removed. I have added another option for those who would rather not enter overview mode or wait until the dock is shown. There is now an option under the 'Autohide Options' section (see the Behavior tab) to limit the pressure sensing trigger to slower mouse speeds. In other words, attacking the edge of the screen with a quick mouse stroke will allow the mouse to pass through the barrier.

Please test it out by downloading the second-monitor-access branch zip at https://github.com/passingthru67/workspaces-to-dock/archive/second-monitor-access.zip and extracting it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com folder. Copy it to your ~/.local/share/gnome-shell/extensions folder and restart Gnome Shell (alt+f2+r).

Don't forget to send me feedback with the best pressure threshold and speed settings so that I can provide reasonable defaults.

**Comment by kubecz3k** [comment]
@passingthru67 I'm very sorry but I'm unable to test version from the zip.. When I install it manually I can't activate the extension. On the gnome extensions website for I'm getting message that zip version of the extension is outdated and I need to update.. Maybe it's related to my gnome version (3.16.4)?

**Comment by passingthru67** [comment]
Would you explain step by step how you are installing it.

**Comment by passingthru67** [comment]
Oops. I missed the info about your Gnome version. Yes, you will need to update to Gnome Shell 3.18 to test the latest changes. I would like to backport it later, once I know its working without issues. Let me know, though, if you're not able to update to 3.18 any time soon. I may push ahead with the backport sooner rather than later.

**Comment by kubecz3k** [comment]
@passingthru67 I will not update to 3.18 since I'm also using this machine for work, and I'm pretty happy with it's current stability and lack of problems (I'm on Ubuntu here, prefer to not to modify software to much, since this usually gives me troubles). Also while it would be more straightforward to have this feature, I'm currently using one of the workarounds that you proposed couple hours ago and It's already step forward for me. Thanks a lot for this extension :).

**Comment by passingthru67** [comment]
I thought I'd go ahead and attempt a backport of this feature while it was fresh on my mind. Turns out it was easier than I expected.

@kubecz3k: If you would like to test it in 3.16, download the second-monitor-access-316 branch at https://github.com/passingthru67/workspaces-to-dock/archive/second-monitor-access-316.zip and follow the above procedures for installing it manually.

Let me know how it turns out. I'd like to know if it actually helps to access the second monitor without making it difficult to access the dock.

**Comment by passingthru67** [comment]
@kubecz3k: Will you be able to test the second-monitor-access-316 branch?

**Comment by kubecz3k** [comment]
@passingthru67 oh my I totally forgot that you prepared this one (it was quite late when I saw this, wanted to check next day). I will check this branch for sure! Thanks a lot!

**Comment by kubecz3k** [comment]
@passingthru67 I have tested this new feature, it works wonderfully! For now I'm using it on the default 50px setting, don't have problems. I'm little worried if people will be able to recognize what for this option is. Maybe you could put somewhere near some hint about multiple monitor setups?

**Comment by passingthru67** [comment]
@kubecz3k: Thanks for testing the new feature and thanks for the feedback. I'll merge this into the master soon.

**Comment by gliwka** [comment]
Thanks a lot!
