### ISSUE TITLE
Activities menu stops working with caption thumbnails activated

### ISSUE THREAD

**Issue by FMuro** [passingthru67/workspaces-to-dock#52]
Hi @passingthru67 and thanks a lot for this useful extension.

I've detected that this extension sometimes breaks the top left hot corner and the activities menu button. This happens when captions thumbnails are on and you drag one and drop it to another workspace.

I'm running GNOME Shell 3.18.3 under an up-to-date Fedora 23 and I've checked this with all other extensions disabled.

**Comment by passingthru67** [comment]
@FMuro, What version of WtD are you running? Did you manually install from the master branch or did you install from extensions.gnome.org?

**Comment by FMuro** [comment]
Thanks for your quick answer @passingthru67 I'm using the version from extensions.gnome.org

**Comment by passingthru67** [comment]
I believe this might already be fixed in the master branch. Please download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r).

**Comment by FMuro** [comment]
It does work with the update, thanks!
