### ISSUE TITLE
Option addition: Show dock when workspaces are _manually_ switched

### ISSUE THREAD

**Issue by fbruetting** [passingthru67/workspaces-to-dock#73]
This would prevent showing up the dock when switching to applications on other workspaces, but would show it if I switch workspaces specifically.

This would make a difference, because when I switch to a specific application, I know no which workspace it runs and the dock is annoying/superfluous to me. But when I switch one workspace up or down, I mostly search something and therefore the appearing dock would be useful.

**Comment by passingthru67** [comment]
There's an option to show the dock temporarily when switching workspaces. It's a miscellaneous option found under the Behavior tab. Is this what you're describing?

**Comment by fb87** [comment]
Not really, that's why i described it in a bit more detail. Problem is, when I click on an application icon in may dash(to dock), I'm switching to an application and it's corresponding workspace – therefore I don't need WTD to popup, because I already „found“ my program (and it's workspace) I was looking for. But when I switch workspaces per hotkeys, I am usually searching for something (mostly a free workspace) – so here the appearing WTD would be nice (because I have an overview of all workspaces).

So while I really often switch workspaces due to application switching, I could save some time if WTD wouldn't appear (and therefore I don't have to wait for it to disappear). But the main reason for me is, that it feels distracting when I don't need the information of what's running in which workspace.

**Comment by passingthru67** [comment]
Let me get this straight .. you only want WtD to show when you are switching workspaces manually with a hotkey. You don't want it to show when you hover/click an icon on DtD. Is that right?  If that's right, then you should uncheck the option to 'Show the dock when hovering over DtD extension'. Also, check the option to 'Show dock temporarily when switching workspaces' so that the dock appears even when it normally would be dodging a window. That should provide the functionality you're describing.

On the other hand, if you want WtD to remain hidden only when DtD app icon switches to another workspace, you would have to turn off intellihide altogether.

**Comment by fb87** [comment]
This deactivates the dock, getting shown automatically at all. I meant maybe it's useful to only show it, when an application in DtD (ar Alt+Tab, etc.) is clicked, so you see to which workspace you're switching. Because when switching manually, you know where you're switching to. But it's not that important, just want to propose a small option. :)
